#!/bin/bash

IP=$(echo "$QUERY_STRING" | sed -n 's/^ip=\([^&]*\).*$/\1/p' | sed 's/%3A/:/g')
TYPE=$(echo "$QUERY_STRING" | sed -n 's/^.*type=\([^&]*\).*$/\1/p' | sed "s/%20/ /g")

if [ $IP ] && [ $TYPE ]
then
    echo -e "Content-type: text/html\n\n<!DOCTYPE html>

<html>
<head>

  <title>dig $IP $TYPE</title>
</head>

<body>
<pre>"
    if dig $IP $TYPE
    then
        echo -e "</pre>\n"
        echo -e "<hr />\n"
        echo -e "<a href=\"/\">Main page</a>\n"
        echo -e "</body>\n</html>"
    else
        echo -e "</pre>\n"
        echo -e "There was a problem. Go back to the <a href=\"/\">Main page</a>.\n"
        echo -e "</body>\n</html>"
    fi
    else
        echo -e "Location: /\n"
fi


