#!/bin/bash

IP=$(echo "$QUERY_STRING" | sed -n 's/^.*ip=\([^&]*\).*$/\1/p' | sed 's/%3A/:/g')

if [ $IP ]
then
    echo -e "Content-type: text/html\n\n<!DOCTYPE html>

<html>
<head>

  <title>whois $IP</title>
</head>

<body>
<pre>"
    if whois $IP
    then
        echo -e "</pre>\n"
        echo -e "<hr />\n"
        echo -e "<a href=\"/\">Main page</a>\n"
        echo -e "</body>\n</html>"
    else
        echo -e "</pre>\n"
        echo -e "There was a problem. Go back to the <a href=\"/\">Main page</a>.\n"
        echo -e "</body>\n</html>"
    fi
    else
        echo -e "Location: /\n"
fi

